server {
    listen 8080; # <--- Puerto no privilegiado para el usuario 'bolo'
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Vital para el routing de React
    }
}